#baseURL: https://jeanmi05.github.io/Azimut
baseURL: https://azimuter.netlify.app/
title: Des guides touristiques numériques pour être libre et autonome.
theme: Azimut
enableEmoji: true
enableGitInfo: true
paginate: 6
summaryLength: 10

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
  - name: categories
    weight: 80
  - name: date
    weight: 10