baseURL: http://example.org/
languageCode: en-us
title: Des guides touristiques numériques pour être libre et autonome.
theme: Azimut
enableEmoji: true
enableGitInfo: true
paginate: 6
summaryLength: 10
