main:
 - identifier: A propos
   name: A propos
   url: /a-propos
   weight: 100
 - identifier: Guides touristiques
   name: Guides touristiques
   url: /Guides-touristiques
   weight: 200
 - identifier: Blog
   name: Blog
   url: /Blog
   weight: 300
 - identifier: Contact
   name: Contact
   url: /contact
   weight: 400
 - identifier: Categories
   name: Categories
   url: /Categories
   weight: 500

social:
  - identifier: GitHub
    name: GitHub
    url: https://github.com/VotreCompteGithub
    pre: <i class='fab fa-github'></i>
  - identifier: Twitter
    name: Twitter
    url: https://twitter.com/VotreCompteTwitter
    pre: <i class='fab fa-twitter'></i>
  - identifier: Facebook
    name: Facebook
    url: https://facebook.com
    pre: <i class="fa-brands fa-facebook"></i>

   
footer:
  - identifier: Protection des données
    name: Protection des données
    url: /protection-des-donnees
  