# IMPORTANT
# Toutes les clés de configuration au niveau du site sont stockées en minuscules
# doit être accédé avec {{if isset .Site.Params "myparam"}}
# et non avec {{if isset .Site.Params "myParam"}}
#
#color: "#4f46e5"
primaryColor: "#246a77"
googleFont: "Roboto"
linkColor: "Pink"
author: "Jean-Michel EVEN"
#authorImage: "/images/avatar.jpg"
brand: Azimuter
description: "Des guides touristiques numériques pour être libre et autonome. En accès libre et gratuit, sans login ni mot de passe. Just click and travel"