[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.107.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://azimuter.netlify.app"
  to = "https://azimuter.com"
  status = 301
  force = true

[[redirects]]
  from = "http://azimuter.com"
  to = "https://azimuter.com"
  status = 301
  force = true

  [[redirects]]
  from = "http://www.azimuter.com"
  to = "https://azimuter.com"
  status = 301
  force = true